### ISSUE TITLE
Fix: CORS 문제 해결 필요성

### ISSUE THREAD

**Issue by rla124** [SejongACME/acme#1]
현재 freeboard와 ACME server 연동 시 네트워크 측면에서 cors 문제가 있습니다.
(cors 문제 때문에 데이터를 받아올 수가 없는 상황이었던 것 같습니다.)
(서버 수정이 필요합니다.)

지금 서버가 Flask 프레임워크 기반으로 동작하고 있어서 아래와 같은 시도를 해보았지만 아직 해결이 안되었습니다. 
1. flask-cors
2. response header에 Access-Control-Allow-Origin 선언 후 클라이언트 Origin과 비교 

![cors](https://github.com/SejongACME/acme/assets/126058381/ed5c635b-b235-4b55-a62a-d1f933a0a898)

저희와 동일한 문제에 직면한 사례가 있어 링크를 첨부하였습니다. 
https://github.com/ankraft/ACME-oneM2M-CSE/issues/93

**Comment by KyeongD** [comment]
acme.ini 파일에

[http.cors]
enable=true

추가하면 문제 해결할 수 있습니다.

**Comment by rla124** [comment]
감사합니다~
말씀해주신 방법과
cors를 우회하는 ip 주소로 접속해서 문제를 해결했습니다.
